#!/usr/bin/env python3
"""Point .vscode/mcp.json at this machine's virtualenv interpreter.

Why this exists rather than a committed mcp.json: a venv puts its interpreter in
bin/python on Linux and Scripts\\python.exe on Windows, and unlike launch.json the
MCP configuration schema has no per-platform conditional -- the stdio fields are
only type, command, args, cwd, env, envFile, dev and sandboxEnabled. So one
committed file cannot name a working interpreter on both, and the file is
therefore generated by setup.sh / setup.ps1 and kept out of source control.

Only the "screenshot" entry is replaced. Everything else in the file is
preserved, including other servers and the inputs array, because this is a
workspace file the user is invited to edit.

Both setup scripts call this with the interpreter they just built:

    python write_mcp_config.py [CONFIG] [INTERPRETER]

CONFIG defaults to <repository root>/.vscode/mcp.json and INTERPRETER to this
platform's path inside <repository root>/.mcp/screenshot/.venv.
"""

import json
import sys
from pathlib import Path

# This file lives at <root>/.mcp/screenshot/, so the repository root is two
# levels up. Derived from __file__ rather than from the working directory: the
# setup scripts are run from wherever the user happens to be standing.
_HERE = Path(__file__).resolve().parent
_ROOT = _HERE.parent.parent

_CONFIG = _ROOT / ".vscode" / "mcp.json"
_VENV = _HERE / ".venv"
_SERVER = _HERE / "server.py"


def venv_interpreter(platform: str) -> str:
    """Where a virtualenv keeps its interpreter on `platform`.

    Split out and parameterised by platform so the Windows answer can be checked
    from Linux -- the branch is otherwise only reachable on a machine this
    repository may never be tested on.
    """
    if platform == "win32":
        return "Scripts/python.exe"
    return "bin/python"


def server_command(platform: str) -> str:
    """The `command` value for mcp.json on `platform`.

    Written in terms of ${workspaceFolder} so the generated file stays portable
    within a clone: moving or renaming the checkout does not invalidate it, which
    is the property that makes committing a *template* worth avoiding rather than
    committing an absolute path.
    """
    return "${workspaceFolder}/.mcp/screenshot/.venv/" + venv_interpreter(platform)


def server_args() -> list[str]:
    return ["${workspaceFolder}/.mcp/screenshot/server.py"]


def update(config_path: Path, command: str) -> int:
    """Replace the screenshot server entry in `config_path`, preserving the rest."""
    try:
        config = json.loads(config_path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        config = {}
    except json.JSONDecodeError as exc:
        # Refusing beats rewriting: the file may be half-edited, and a valid file
        # the user is in the middle of changing is not ours to discard.
        print(
            f"warning: {config_path} is not valid JSON ({exc}); "
            f"leaving it alone, so the MCP command may need setting by hand",
            file=sys.stderr,
        )
        return 1

    if not isinstance(config, dict):
        print(f"warning: {config_path} is not a JSON object; leaving it alone",
              file=sys.stderr)
        return 1

    servers = config.get("servers")
    if not isinstance(servers, dict):
        servers = {}
        config["servers"] = servers
    servers["screenshot"] = {
        "type": "stdio",
        "command": command,
        "args": server_args(),
    }
    # Present in every file VS Code writes, and its absence is the kind of
    # difference that shows up as a spurious diff the first time VS Code
    # rewrites the file itself.
    config.setdefault("inputs", [])

    config_path.parent.mkdir(parents=True, exist_ok=True)
    config_path.write_text(json.dumps(config, indent=4) + "\n", encoding="utf-8")
    print(f"registered the screenshot MCP server: {config_path} -> {command}",
          file=sys.stderr)
    return 0


def main(argv: list[str]) -> int:
    config_path = Path(argv[1]) if len(argv) > 1 else _CONFIG
    command = argv[2] if len(argv) > 2 else server_command(sys.platform)
    return update(config_path, command)


if __name__ == "__main__":
    sys.exit(main(sys.argv))
