# EmbedSpirv.cmake - turn compiled SPIR-V modules into a C++ header.
#
# Run as a script:
#   cmake -DVKG_EMBED_OUTPUT=<header> \
#         "-DVKG_EMBED_NAMES=gear_vert_spv;gear_frag_spv" \
#         "-DVKG_EMBED_FILES=<a.spv>;<b.spv>" \
#         -P EmbedSpirv.cmake
#
# Written in CMake rather than Python so a Windows build only needs the
# compiler, CMake and the Vulkan SDK.

if(NOT DEFINED VKG_EMBED_OUTPUT)
    message(FATAL_ERROR "EmbedSpirv.cmake: VKG_EMBED_OUTPUT is required")
endif()
if(NOT DEFINED VKG_EMBED_NAMES OR NOT DEFINED VKG_EMBED_FILES)
    message(FATAL_ERROR "EmbedSpirv.cmake: VKG_EMBED_NAMES and VKG_EMBED_FILES are required")
endif()

list(LENGTH VKG_EMBED_NAMES nameCount)
list(LENGTH VKG_EMBED_FILES fileCount)
if(NOT nameCount EQUAL fileCount)
    message(FATAL_ERROR "EmbedSpirv.cmake: ${nameCount} names but ${fileCount} files")
endif()

set(header "// Generated by cmake/EmbedSpirv.cmake - do not edit.\n")
string(APPEND header "#ifndef VKGEARS_SPIRV_EMBEDDED_H\n")
string(APPEND header "#define VKGEARS_SPIRV_EMBEDDED_H\n\n")
string(APPEND header "#include <cstddef>\n#include <cstdint>\n\n")
string(APPEND header "namespace vkg {\nnamespace spirv {\n\n")

math(EXPR lastIndex "${nameCount} - 1")

foreach(index RANGE 0 ${lastIndex})
    list(GET VKG_EMBED_NAMES ${index} moduleName)
    list(GET VKG_EMBED_FILES ${index} moduleFile)

    if(NOT EXISTS "${moduleFile}")
        message(FATAL_ERROR "EmbedSpirv.cmake: ${moduleFile} does not exist")
    endif()

    # Read the module as hex text: two characters per byte, no separators.
    file(READ "${moduleFile}" hex HEX)
    string(LENGTH "${hex}" hexLength)
    math(EXPR byteCount "${hexLength} / 2")
    if(byteCount EQUAL 0)
        message(FATAL_ERROR "EmbedSpirv.cmake: ${moduleFile} is empty")
    endif()
    if(NOT byteCount EQUAL 0)
        math(EXPR remainder "${byteCount} % 4")
        if(NOT remainder EQUAL 0)
            message(FATAL_ERROR "EmbedSpirv.cmake: ${moduleFile} is not a multiple of 4 bytes")
        endif()
    endif()

    # SPIR-V is a stream of 32 bit words, little endian.
    math(EXPR wordCount "${hexLength} / 8")
    math(EXPR lastWord "${wordCount} - 1")

    string(APPEND header "// ${moduleFile} (${byteCount} bytes, ${wordCount} words)\n")
    string(APPEND header "static const uint32_t ${moduleName}[] = {\n")

    set(line "    ")
    set(perLine 0)
    foreach(word RANGE 0 ${lastWord})
        math(EXPR offset "${word} * 8")
        string(SUBSTRING "${hex}" ${offset} 8 digits)
        # The file holds little endian words; reorder the four byte pairs back
        # into the numeric value the C++ array must contain.
        string(SUBSTRING "${digits}" 0 2 byte0)
        string(SUBSTRING "${digits}" 2 2 byte1)
        string(SUBSTRING "${digits}" 4 2 byte2)
        string(SUBSTRING "${digits}" 6 2 byte3)
        string(APPEND line "0x${byte3}${byte2}${byte1}${byte0}u, ")
        math(EXPR perLine "${perLine} + 1")
        if(perLine EQUAL 8)
            string(APPEND header "${line}\n")
            set(line "    ")
            set(perLine 0)
        endif()
    endforeach()
    if(NOT perLine EQUAL 0)
        string(APPEND header "${line}\n")
    endif()

    string(APPEND header "};\n")
    string(APPEND header "static const size_t ${moduleName}_size = ${byteCount};\n\n")
endforeach()

string(APPEND header "} // namespace spirv\n")
string(APPEND header "} // namespace vkg\n\n")
string(APPEND header "#endif // VKGEARS_SPIRV_EMBEDDED_H\n")

file(WRITE "${VKG_EMBED_OUTPUT}" "${header}")
